/**
 * Synthetic AML alerts.
 *
 * Four cases chosen to cover the dispositions an analyst actually reaches: a
 * clear escalation, a name match that dissolves under scrutiny, a false positive
 * generated by a blunt rule, and a genuinely ambiguous case that should end in a
 * request for information rather than a decision. A demo where every case
 * escalates would prove nothing about judgement.
 *
 * All customers, counterparties and account numbers are invented.
 */

export interface DemoTransaction {
    date: string;
    /** Positive is money in, negative is money out. */
    amount: number;
    channel: "cash" | "wire" | "ach" | "check" | "card";
    counterparty: string;
    counterpartyCountry: string;
    memo?: string;
}

export interface AmlCase {
    id: string;
    label: string;
    /** One line shown on the case picker, before the visitor commits to a run. */
    summary: string;
    alertRule: string;
    customer: {
        name: string;
        accountNumber: string;
        type: "personal" | "business";
        businessType?: string;
        relationshipOpened: string;
        expectedMonthlyVolume: number;
        priorSarCount: number;
    };
    transactions: DemoTransaction[];
    analystNotes?: string;
}

export const amlCases: AmlCase[] = [
    {
        id: "structuring",
        label: "Cash deposits below reporting threshold",
        summary: "Nine cash deposits in eleven days, each just under $10,000.",
        alertRule: "RULE-014 · Cash structuring — multiple deposits below CTR threshold",
        customer: {
            name: "Harbor Point Auto Detailing LLC",
            accountNumber: "****4471",
            type: "business",
            businessType: "Automotive detailing (cash-intensive)",
            relationshipOpened: "2023-02-14",
            expectedMonthlyVolume: 45000,
            priorSarCount: 0,
        },
        transactions: [
            { date: "2025-06-02", amount: 9400, channel: "cash", counterparty: "Branch 118 — Teller", counterpartyCountry: "US" },
            { date: "2025-06-03", amount: 9200, channel: "cash", counterparty: "Branch 118 — Teller", counterpartyCountry: "US" },
            { date: "2025-06-04", amount: 9750, channel: "cash", counterparty: "Branch 204 — ATM", counterpartyCountry: "US" },
            { date: "2025-06-06", amount: 9600, channel: "cash", counterparty: "Branch 118 — Teller", counterpartyCountry: "US" },
            { date: "2025-06-07", amount: 9350, channel: "cash", counterparty: "Branch 331 — Teller", counterpartyCountry: "US" },
            { date: "2025-06-09", amount: 9800, channel: "cash", counterparty: "Branch 204 — ATM", counterpartyCountry: "US" },
            { date: "2025-06-10", amount: 9500, channel: "cash", counterparty: "Branch 118 — Teller", counterpartyCountry: "US" },
            { date: "2025-06-12", amount: 9250, channel: "cash", counterparty: "Branch 331 — Teller", counterpartyCountry: "US" },
            { date: "2025-06-13", amount: 9700, channel: "cash", counterparty: "Branch 118 — Teller", counterpartyCountry: "US" },
            { date: "2025-06-13", amount: -84000, channel: "wire", counterparty: "Cascade Equipment Leasing", counterpartyCountry: "US", memo: "Equipment purchase" },
        ],
        analystNotes:
            "Deposits are spread across three branches and two channels. Business is cash-intensive, but declared monthly volume is $45k and June deposits total $85.5k in under two weeks.",
    },
    {
        id: "sanctions-near-match",
        label: "Outbound wire to a near-match counterparty",
        summary: "A $240,000 wire to a name one character off a listed entity.",
        alertRule: "RULE-002 · Sanctions screening — fuzzy name match above threshold",
        customer: {
            name: "Delta Ridge Commodities Inc",
            accountNumber: "****8823",
            type: "business",
            businessType: "Agricultural commodity export",
            relationshipOpened: "2019-08-01",
            expectedMonthlyVolume: 1200000,
            priorSarCount: 0,
        },
        transactions: [
            { date: "2025-05-28", amount: -240000, channel: "wire", counterparty: "Volkov Maritime Holdings", counterpartyCountry: "Cyprus", memo: "Charter hire — grain vessel" },
            { date: "2025-05-14", amount: 610000, channel: "wire", counterparty: "Prairie Grain Cooperative", counterpartyCountry: "US", memo: "Settlement" },
            { date: "2025-05-02", amount: -185000, channel: "wire", counterparty: "Aegean Shipping Services", counterpartyCountry: "Greece", memo: "Charter hire" },
        ],
        analystNotes:
            "Customer charters vessels routinely; prior charter payments to Greek and Maltese operators cleared without issue. Counterparty name resembles a listed entity.",
    },
    {
        id: "payroll-false-positive",
        label: "Velocity alert on a payroll account",
        summary: "Forty-one outbound ACH credits in one day, all round amounts.",
        alertRule: "RULE-031 · Transaction velocity — outbound count exceeds profile",
        customer: {
            name: "Sierra Vista Staffing Group",
            accountNumber: "****1190",
            type: "business",
            businessType: "Temporary staffing agency",
            relationshipOpened: "2017-03-22",
            expectedMonthlyVolume: 890000,
            priorSarCount: 0,
        },
        transactions: [
            { date: "2025-06-15", amount: 412000, channel: "wire", counterparty: "Client remittance — Northgate Foods", counterpartyCountry: "US", memo: "Invoice 20418" },
            { date: "2025-06-16", amount: -2400, channel: "ach", counterparty: "Payroll — employee 0114", counterpartyCountry: "US", memo: "Semi-monthly payroll" },
            { date: "2025-06-16", amount: -1850, channel: "ach", counterparty: "Payroll — employee 0115", counterpartyCountry: "US", memo: "Semi-monthly payroll" },
            { date: "2025-06-16", amount: -3100, channel: "ach", counterparty: "Payroll — employee 0116", counterpartyCountry: "US", memo: "Semi-monthly payroll" },
            { date: "2025-06-16", amount: -2750, channel: "ach", counterparty: "Payroll — employee 0117", counterpartyCountry: "US", memo: "Semi-monthly payroll" },
            { date: "2025-06-16", amount: -2200, channel: "ach", counterparty: "Payroll — employee 0118", counterpartyCountry: "US", memo: "Semi-monthly payroll" },
        ],
        analystNotes:
            "Alert fired on outbound count (41 items). Pattern repeats on the 1st and 16th of every month for the past eight years. Sample of six items shown.",
    },
    {
        id: "trade-ambiguous",
        label: "Round-dollar wires through a transit jurisdiction",
        summary: "Three round-figure payments to a new intermediary in a high-risk jurisdiction.",
        alertRule: "RULE-022 · Geographic risk — round-value wires to high-risk jurisdiction",
        customer: {
            name: "Continental Machine Parts Corp",
            accountNumber: "****5507",
            type: "business",
            businessType: "Industrial parts distribution",
            relationshipOpened: "2021-11-05",
            expectedMonthlyVolume: 340000,
            priorSarCount: 1,
        },
        transactions: [
            { date: "2025-06-04", amount: -75000, channel: "wire", counterparty: "Anchor Trade Capital Ltd", counterpartyCountry: "Seychelles", memo: "Advance — PO 88214" },
            { date: "2025-06-11", amount: -100000, channel: "wire", counterparty: "Anchor Trade Capital Ltd", counterpartyCountry: "Seychelles", memo: "Advance — PO 88231" },
            { date: "2025-06-19", amount: -125000, channel: "wire", counterparty: "Anchor Trade Capital Ltd", counterpartyCountry: "Seychelles", memo: "Advance — PO 88247" },
            { date: "2025-06-20", amount: 96000, channel: "wire", counterparty: "Redwood Industrial Supply", counterpartyCountry: "US", memo: "Customer payment" },
        ],
        analystNotes:
            "Counterparty was added to the customer's payee list six weeks ago. Prior SAR (2023) related to an unrelated cash pattern and was closed with no law-enforcement follow-up.",
    },
];
